Kinvey/android-sdk

android-lib/src/com/kinvey/android/offline/AbstractSyncService.java
java-api-core/src/com/kinvey/java/query/KinveyClientErrorCode.java

Adding ability to provide APP_KEY and APP_SECRET as service metadata
manually tested

Adding ability to provide APP_KEY and APP_SECRET as service metadata

---

android-lib/src/main/java/com/kinvey/android/store/DataStore.java

move client to last parameter for DataStore
move client to last parameter for DataStore
manual tests/ DataStore jUnit tests

fixed java doc for DataStore#collection signature

---

android-lib/build.gradle

bump api version
bump api version
Manual tests

MLIBZ-1672 changed minSDK version

---

android-lib/android-lib.iml
android-lib/build.gradle
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java
java-api-core/java-api-core.iml
java-api-core/src/com/kinvey/java/store/BaseUserStore.java
java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java
java-api-core/src/com/kinvey/java/store/requests/user/LogoutRequest.java

App was crashing on Realm acquiring new instance of realm, while last one was no cleared
Add control over realm instances, add finally clauses for most of realm operations
Manual Tests

Mlibz 1686 crash on logout

---

android-lib/src/com/kinvey/android/offline/AbstractSqliteOfflineStore.java
android-lib/src/com/kinvey/android/offline/OfflineTable.java

SQLile does not accept `-` as and character of table name 
escape table name to avoid problems with special characters
manual testing

added symbol " ' " to SQLite operation with table name

---

android-lib/src/com/kinvey/android/Client.java

Add new constructor that accept input stream as the source of properties
Add new constructor that accept input stream as the source of properties
manual tests

Mlibz 1571 ver2.x gcm breaks

---

android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/AbstractClient.java

new constructor to pass properties
new constructor to pass properties
manual

migrate constructors from 2.x ver

---

android-lib/src/main/java/com/kinvey/android/callback/KinveyDeleteCallback.java

JAVADoc changes for KinveyDeleteCallback
JAVADoc changes for KinveyDeleteCallback
checked on devcenter

add javadoc to KinveyDeleteCallback

---

android-lib/src/main/AndroidManifest.xml
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/push/AbstractPush.java
android-lib/src/main/java/com/kinvey/android/push/GCMPush.java
android-lib/src/main/java/com/kinvey/android/push/KinveyGCMService.java

fix push registration
fix push registration
manual tests

Mlibz 1811 push registration poblem

---

android-lib/src/com/kinvey/android/Client.java
android-lib/src/com/kinvey/android/push/AbstractPush.java
android-lib/src/com/kinvey/android/push/GCMPush.java
android-lib/src/com/kinvey/android/push/KinveyGCMService.java

fix push register/unregister
merge changes from 3.x
manual tests

Mlibz 1811 ver2.x push registration poblem

---

android-lib/src/androidTest/assets/kinvey.properties
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java
java-api-core/test/com/kinvey/java/UserGroupTest.java
java-api-core/test/com/kinvey/java/UserTest.java

Add new Users tests
New tests for Log In, Sign Up, Log Out, Email Verification, Password Update, Forgot username, Social networks
JUnit

feat: MLIBZ-1865 Unit Test Users (Android v3)

---

android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

do not create cache when network store type selected
do not create cache when network store type selected
manual tests

create cache for all StoreTypes except StoreType.Network

---

README.md
android-lib/android-lib.iml
build.gradle
java-api-core/java-api-core.iml
java-api-core/src/com/kinvey/java/core/KinveyHeaders.java
samples/build.gradle
settings.gradle

update readme to latest changes
update readme to latest chaneges

Ver3.0 update readme

---

build.gradle

Remove the "Beta"
(https://kinvey.atlassian.net/browse/MLIBZ-1878)
- Remove the "Beta" tag from Android v3 in every place (platform dropdown, downloads, changelog etc)
JUnit

feat: MLIBZ-1878 Docs for Android GA

---

android-lib/src/main/java/com/kinvey/android/AsyncCustomEndpoints.java
java-api-core/src/com/kinvey/java/CustomEndpoints.java

Endpoint returning an array of objects with a casting error (https://kinvey.atlassian.net/browse/MLIBZ-1882)
Return List instead of array for CustomEndpoints
Manual

fix: MLIBZ-1882 Android 3.0.0 Beta-3 - Endpoint returning an array of objects with a casting error

---

android-lib/src/main/java/com/kinvey/android/cache/QueryHelper.java

Add missed local operator "and"
Added missed local operator "and"
JUnit

feat: MLIBZ-1913 Add Local operator "and(query)" to Android SDK 3.0

---

android-lib/src/androidTest/java/com/kinvey/androidTest/CustomEndpointsTest.java

Add Custom Endpoints tests
(https://kinvey.atlassian.net/browse/MLIBZ-1907)
Added tests for Custom Endpoints
JUnit

feat: MLIBZ-1907 Unit Test Custom Endpoints (Android v3)

---

android-lib/build.gradle
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/test/java/com/kinvey/android/QueryTest.java
android-lib/src/test/java/com/kinvey/android/RealmTest.java
android-lib/src/test/java/com/kinvey/android/util/LibraryProjectTestRunner.java
android-lib/src/test/java/com/kinvey/android/util/Person.java
android-lib/src/test/java/com/kinvey/android/util/PersonRepository.java
android-lib/src/test/java/com/kinvey/android/util/PersonRepositoryImpl.java

Add DataStore tests 
(https://kinvey.atlassian.net/browse/MLIBZ-1864)
Added more Instrumented tests, Unit tests for Realm
JUnit

feat: MLIBZ-1864 Unit Test DataStore (Android v3)

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java

Add new FileStore tests
New tests for upload (File, InputStream, publicly readable files), download, cancel uploading, cancel downloading, upload progress changing, download progress changing, 
JUnit

feat: MLIBZ-1867 Unit Test FileStore (Android v3)

---

android-lib/src/androidTest/java/com/kinvey/androidTest/CustomEndpointsTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/async/AsyncTaskTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/ClientCacheTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/KinveyHandlerThread.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java
java-api-core/src/com/kinvey/java/store/BaseFileStore.java

Fix memory leaks
Terminate HandlerThread after tests, close stream, remove files after tests
JUnit

feat: MLIBZ-1926 Research File Descriptor issues in Android tests

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java

Update saving file's metadata to cache
Update saving file's metadata to cache
JUnit

fix: MLIBZ-1889 File's 'public' value is not saved

---

android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java

Logout fails because Realm wasn't closed
Close Realm if there're some exceptions
Instrumented

fix: MLIBZ-1947 On logout, the Realm instance is still running and the logout attempt fails.

---

android-lib/src/androidTest/java/com/kinvey/androidTest/ClientBuilderTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/core/AbstractKinveyClient.java

Return Client.Builder
Changed return type
JUnit

feat: MLIBZ-1980 Problem with the Kinvey Android setDeltaSetCache method

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/model/User.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/store/BaseUserStore.java
java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java
java-api-core/src/com/kinvey/java/store/requests/user/Retrieve.java
java-api-core/src/com/kinvey/java/store/requests/user/RetrieveUsers.java

Fixed Cast errors in UserStore
Fixed Cast errors in UserStore, added 'retrieve' tests
Instrumented

fix: MLIBZ-1996 UserStore Retrieve User throwing Cast Exception

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/PushRequest.java

Add syncCount method in DataStore
Added syncCount method, added Instrumented test for this method
Instrumented

feat: MLIBZ-1993 Sync Count Not Impelemented for DataStore

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
java-api-core/src/com/kinvey/java/model/KinveyMetaData.java

Fix saving kmd to cache
Fix saving kmd to cache and add tests
Instrumented

feat: MLIBZ-2033 Delta Set Caching not working correctly

---

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryWithRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
java-api-core/src/com/kinvey/java/model/KinveyMetaData.java

Fix "_acl" is not saved issue
Fixed "_acl" is not saved issue
Instrumented

fix: MLIBZ-2067 '.in' query throws an Exception when used with '.pull()' in SYNC store.

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/DefaultKinveyClientCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/DefaultKinveyListCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/DefaultKinveyPullCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/DefaultKinveyPushCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/QueryHelper.java

Implement  saving list of primitives to realm
Update creating realm scheme, saving object to realm, getting data from realm to object

feat: Implement support list of primitives saving in realm

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheTTLTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryResultTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyClientCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyListCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyPullCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/BooleanPrimitiveListInPerson.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/FloatPrimitiveListInPerson.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/IntegerPrimitiveListInPerson.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/ObjectListInPerson.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/StringGenericJson.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/StringPrimitiveListInPerson.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/QueryHelper.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
java-api-core/src/com/kinvey/java/model/KinveyMetaData.java
java-api-core/test/com/kinvey/java/model/ACLTest.java

Improve the work "in" operator in RealmCache#get(Query) method
Improved the work "in" operator in RealmCache#get(Query) method
Instrumented

feat: Improve operator in

---

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java
android-lib/src/main/java/com/kinvey/android/cache/QueryHelper.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
java-api-core/src/com/kinvey/java/model/KinveyMetaData.java

Update "in" operator for more than one search parameter
Update logic for "in" operator
Instrumented, manual in Book sample

feat: Update "in" operator for more than one search parameter

---

android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListRequest.java
java-api-core/src/com/kinvey/java/sync/SyncManager.java

Add DataStore#save(ListOfEntities) method
Added new method DataStore.save for saving list of entities
Instrumented

feat: Add DataStore#save(ListOfEntities) method

---

README.md

Update Android repo Readme
Added Test running and Contributing sections

feat: Update Android repo Readme

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/async/AsyncPushRequest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/cache/ICacheManager.java
java-api-core/src/com/kinvey/java/network/NetworkManager.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/PushRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/delete/AbstractDeleteRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteIdsRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteQueryRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteSingleRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/save/SaveRequest.java
java-api-core/src/com/kinvey/java/sync/RequestMethod.java
java-api-core/src/com/kinvey/java/sync/SyncManager.java
java-api-core/src/com/kinvey/java/sync/dto/SyncItem.java
java-api-core/src/com/kinvey/java/sync/dto/SyncRequest.java

Change logic for Sync Requests saving
Removed saving full object to Sync cache 
Moved Sync requests initialization before pushing items to server
Instrumented

feat: MLIBZ-2073 Change logic for Sync Requests saving

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/query/AbstractQuery.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/test/com/kinvey/java/NetworkFileManagerTest.java

The auto-pagination feature was not available for the `pullBlocking` method
Add auto-pagination to `pullBlocking`.
Add integration test.

MLIBZ-2135 Auto-pagination for blocking pull

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/read/AbstractReadCountRequest.java

Implemented DataStore#clear method
Added DataStore#clear method for clearing the local cache.

feat: MLIBZ-2132 Implement DataStore#clear

---

android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java
android-lib/src/main/java/com/kinvey/android/cache/TableNameManager.java

Clear collection if class model was changed
Added logic: if the class model is changed the table with this class will be recreated (old table will be deleted) and sync collections will be clearing as well.
Manual

feat: MLIBZ-2184 Crash for sync collection when model is changed

---

android-lib/src/androidTest/java/com/kinvey/androidTest/model/Author.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/util/RealmUtil.java
android-lib/src/androidTest/java/com/kinvey/androidTest/util/TableNameManagerUtil.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
android-lib/src/main/java/com/kinvey/android/cache/TableNameManager.java

Added cascade delete
Added cascade delete
Instrumented

feat: MLIBZ-2155  data store.clear() throws an (implicit, non crashing) exception

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyClientCallback.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java

Fixed cascade delete for arrays
Fixed cascade delete for arrays
Instrumented

feat: MLIBZ-2195 Fix cascade delete for arrays

---

android-lib/javadoc/overview.html

Fixing outdated links to documentation.
A total of 4 links were changes in an HTML file.
Manual testing.

Outdated links to guides.

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/util/RealmCacheManagerUtil.java
android-lib/src/androidTest/java/com/kinvey/androidTest/util/TableNameManagerUtil.java

Add instrumented test
Added:
1. Check that collection is cleared after changing class hash (it happens when model class was changed);
2. Check that items in support tables don't grow exponentially after pull; 
3. Check that item are saved in inner and support tables, like kmd and acl and like book_author table;
4. Check that all support tables were initialization in correct way.
Instrumented

feat: MLIBZ-2193 Add unit and instrumented tests around realm db state after operations

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveySyncCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java

Added instrumented tests for CRUD operations (sync and async) with delta set caching enabled. 
Added instrumented tests for delta set caching.
Instrumented

feat: MLIBZ-2279 Add tests for CRUD operations with delta set caching enabled

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/read/AbstractReadCountRequest.java

Added cached callback to DataStore#count
Added cached callback to DataStore#count
Instrumented

feat: MLIBZ-2143 Add cached callback to DataStore#count

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

Moved setDeltaCache to DataStore
Moved setDeltaCache to DataStore. Client#setDeltaCache was marked as deprecated. Updated tests to Delta Cache.
Instrumented.

feat: MLIBZ-2286 Move setDeltaCache to DataStore

---

android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java

Added cascade deleting performance improvement
`findAll` changed to `findFirst` in the query to realm table in cascade deleting function.

feat: MLIBZ-2301 Add cascade deleting performance improvement

---

java-api-core/build.gradle

Investigate how to integrate PubNub to the SDK. Integrate PubNub library.
Added PubNub library as dependency in the build.gradle.

feat: MLIBZ-2360 Integrate PubNub library

---

java-api-core/build.gradle
java-api-core/src/com/kinvey/java/store/LiveServiceRouter.java
java-api-core/src/com/kinvey/java/store/RealtimeRouter.java

Implement live service router to integrate with pub nub library
Added singleton RealtimeRouter class with initialize and unInitialize methods. 
Will be tested in the MLIBZ-2362 branch with register/unregister methods

feat: MLIBZ-2361 Implement live service router to integrate with PubNub library

---

android-lib/src/androidTest/java/com/kinvey/androidTest/LiveServiceTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/model/LiveModel.java
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/KinveyHeaders.java
android-lib/src/main/java/com/kinvey/android/UuidFactory.java
android-lib/src/main/java/com/kinvey/android/model/User.java
java-api-core/build.gradle
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/dto/DeviceId.java
java-api-core/src/com/kinvey/java/dto/RealtimeRegisterResponse.java
java-api-core/src/com/kinvey/java/store/BaseUserStore.java
java-api-core/src/com/kinvey/java/store/LiveServiceRouter.java
java-api-core/src/com/kinvey/java/store/RealtimeRouter.java
java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java
java-api-core/src/com/kinvey/java/store/requests/user/RealtimeRegisterRequest.java
java-api-core/src/com/kinvey/java/store/requests/user/RealtimeUnregisterRequest.java
java-api-core/test/com/kinvey/java/core/KinveyMockUnitTest.java
java-api-core/test/com/kinvey/java/testing/MockKinveyJsonClient.java
java-lib/src/com/kinvey/nativejava/Client.java

Implement Register/Unregister methods
Added register/unregister methods to User.
Instrumented

feat: MLIBZ-2362 Implement Register/Unregister methods

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/sync/SyncManager.java

Implemented `clear` and `purge` by query.
Added query parameter to `clear` and `purge` methods.
Instrumented

feat: MLIBZ-2144 Implement #clear and #purge by query

---

android-lib/src/androidTest/java/com/kinvey/androidTest/LiveServiceTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyLiveServiceCallback.java
java-api-core/src/com/kinvey/java/store/LiveServiceRouter.java
java-api-core/src/com/kinvey/java/store/requests/user/LogoutRequest.java

Add more tests, add uninitialize to logout
Added uninitialize to logout
Instrumented, manual

feat: MLIBZ-2364 Add uninitialize to logout, add test

---

android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java
android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
java-api-core/src/com/kinvey/java/Constants.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

Change sorting from `_kmd` to `_id`
Changed sort field for pagination for `pull`. Updated sort logic for getting from the cache.
Instrumented

feat: MLIBZ-2318 Change sorting from kmd to id field

---

android-lib/src/androidTest/java/com/kinvey/androidTest/MICLoginTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/AbstractClient.java

Change default MIC API version to v3
Default MIC API version was added 
Instrumented

feat: MLIBZ-2426 Change default mic version to v3

---

android-lib/src/androidTest/java/com/kinvey/androidTest/ClientBuilderTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/Constants.java

Add method for setting instance
Added method for setting instanceID to Client.Builder. 
Instrumented

feat: MLIBZ-2333 Add method for setting instanceID

---

android-lib/build.gradle
android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java
android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
java-api-core/src/com/kinvey/java/Constants.java
java-api-core/src/com/kinvey/java/core/AbstractKinveyQueryCacheReadRequest.java
java-api-core/src/com/kinvey/java/core/AbstractKinveyReadRequest.java
java-api-core/src/com/kinvey/java/model/KinveyAbstractReadResponse.java
java-api-core/src/com/kinvey/java/model/KinveyQueryCacheResponse.java
java-api-core/src/com/kinvey/java/network/NetworkManager.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/QueryCacheItem.java
java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteSingleRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadAllRequest.java
java-api-core/src/com/kinvey/java/store/requests/user/LogoutRequest.java

Update Delta Set realisation
Updated Delta Set mechanism for `DataStore#pull`

feat: MLIBZ-2389 Delta Set implementation

---

android-lib/src/androidTest/java/com/kinvey/androidTest/MICLoginTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/AbstractClient.java

Reverts Kinvey/java-library#153

Revert "feat: MLIBZ-2426 Change default mic version to v3"

---

android-lib/src/androidTest/java/com/kinvey/androidTest/MICLoginTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java
java-api-core/src/com/kinvey/java/AbstractClient.java

Set default MIC API version to v3
Set default MIC API version to v3. Added scope as a parameter to the urlToRender.
Instrumented

feat: MLIBZ-2426 Set default MIC API version to v3

---

android-lib/src/androidTest/java/com/kinvey/androidTest/LiveServiceTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryWithRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyListCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyReadCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/callback/DefaultKinveyReadCallback.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java
android-lib/src/main/java/com/kinvey/android/AsyncPagedPullRequest.java
android-lib/src/main/java/com/kinvey/android/AsyncPullRequest.java
android-lib/src/main/java/com/kinvey/android/callback/KinveyListCallback.java
android-lib/src/main/java/com/kinvey/android/callback/KinveyReadCallback.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
android-lib/src/main/java/com/kinvey/android/sync/KinveyPullResponse.java
java-api-core/src/com/kinvey/java/core/AbstractKinveyClientRequest.java
java-api-core/src/com/kinvey/java/core/AbstractKinveyReadRequest.java
java-api-core/src/com/kinvey/java/model/KinveyReadResponse.java
java-api-core/src/com/kinvey/java/network/NetworkManager.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/AbstractKinveyReadRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/ReadRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/AbstractReadRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadAllRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadIdsRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadQueryRequest.java

Combine logic for pull and find requests. 
Combined logic for pull and find requests. Updated response for find methods, List<T> response  was chnaged to KinveyReadResponse, which contains List<T> result and List<Exception> listOfException fields.
Breaking changes: customers will have to change KinveyListCallback<Entity> to KinveyReadCallback<Entity>.
Instrumented

feat: MLIBZ-2415 Refactor common logic for find and pull implementation

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/PaginationTest.java
android-lib/src/main/java/com/kinvey/android/AsyncPullRequest.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

Add auto-pagination flag parameter to `pull` method
Addу auto-pagination flag parameter to `pull` method
Instrumented

feat: MLIBZ-2483 Add auto-pagination flag parameter to pull method

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java
android-lib/src/androidTest/java/com/kinvey/androidTest/request/HeaderTest.java
android-lib/src/main/java/com/kinvey/android/KinveyHeaders.java
android-lib/src/main/java/com/kinvey/android/UuidFactory.java
java-lib/src/com/kinvey/nativejava/KinveyHeaders.java

Implement new x-kinvey-device-info format.
Added new header `x-kinvey-device-info` to KinveyHeader class. 
Old header `x-kinvey-device-information` was saved.
`x-kinvey-device-info` condains information in json format.
Example:
{
"hv" : 1,
"md" : "Nexus7",
"os" : "Android",
"ov" : "6.0",
"sdk" : "Android", 
"pv" : "3.1.0",
"id" : "32afa46e-227b-399e-bb23-34a7b75dd8f5"
}
Instrumented

feat: MLIBZ-2467 Implement new x-kinvey-device-info format

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

DataStore with AP does not execute Delta Set request
Added auto-pagination request as the first request if delta set and auto-pdagination are enabled
Instrumented

feat: MLIBZ-2533 Make auto-pagination request first if Delta Set and auto-pdagination are enabled

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java

Ignore Delta Set if skip or limit are used in the query.
Added additional query checking to skip and limit, if Delta Set is used.
Instrumented

feat: MLIBZ-2541 Ignore Delta Set if skip or limit are used in the query

---

android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
android-lib/src/main/java/com/kinvey/android/store/DataStore.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java
java-api-core/src/com/kinvey/java/cache/ICache.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/BaseUserStore.java

Add `@NonNull` and `@Nullable` annotations for DataStore and UserStore
Added `@NonNull` and `@Nullable` annotations to `DataStore`, `BaseDataStore`, `RealmCache`, `ICache`, `UserStore/BaseUserStore` classes.
Instrumented

feat: MLIBZ-2474 Add @NonNull and @Nullable annotations for DataStore and UserStore

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java

Add more tests for Delta Set
Added more tests for Delta Set
Instrumented

feat: MLIBZ-2550 Add tests for Delta Set

---

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryTest.java

Add unit tests for `addSort` and `equals` methods.
Added tests for `addSort` and `equals` methods.
Unit tests

feat: MLIBZ-1866 Unit Test Queries  

---

README.md

Outline for how to build the SDK, as well as build a solution to use TLS v1.2 in the SDK.
Actualized build steps.
Added how to enable support for TLSv1.1-1.2.

feat: MLIBZ-2602 Update README.md

---

.travis.yml
android-lib/build.gradle
android-lib/src/androidTest/java/com/kinvey/androidTest/push/GCMReceiver.java
android-lib/src/androidTest/java/com/kinvey/androidTest/push/GCMService.java
android-lib/src/androidTest/java/com/kinvey/androidTest/push/PushTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java
android-lib/src/main/java/com/kinvey/android/Client.java
android-lib/src/main/java/com/kinvey/android/push/AbstractPush.java
android-lib/src/main/java/com/kinvey/android/push/GCMPush.java
gradle.properties

Increase code coverage of push notification source files
Added tests for classes from `com.kinvey.android.push` package. 
Instrumented

feat: MLIBZ-2607 Increase code coverage of push notification source files

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java

The goal of the task is to fix the code to return an object of User for method 'UserStore#get'
'UserStore#get' method returned null in any cases, it was fixed for return User object.
Instrumented

feat: MLIBZ-2653 UserStore#get doesn't return User object fix

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/LinkedDataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/PaginationTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java

Increase code coverage of store source files
Added tests for DataStore, LinkedDataStore, FilesTore, UserStore. 
Tests for deprecated mwthods weren't added.
Filed bugs: `MLIBZ-2653`, `MLIBZ-2654`
Instrumented

feat: MLIBZ-2610 Increase code coverage of store source files

---

android-lib/src/main/java/com/kinvey/android/store/UserStore.java

The goal of the task is to fix login with invalid auth token by UserStore#loginKinveyAuthToken method
UserStore#loginKinveyAuthToken added in a deprecation
Instrumented

feat: MLIBZ-2654 - UserStore#loginKinveyAuthToken logs in user if invalid auth token is used and the user was logged out before this

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java

The goal of the task is to delete overwrite logic of refresh_token after call UserStore#retrieve
Added test for checking that refresh_token is not overridden after call retrieve()
Instrumented

MLIBZ-2657 Getting user metadata from the server overwrites the stored refresh_token

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java

Proper exception handling during MIC auth flow
Add KinveyExeption in the method which process redirect_uri
Instrumented

MLIBZ-2679 Proper exception handling during MIC auth flow

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/CustomEndpointsTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/cache/QueryWithRealDataTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/network/QueryNetworkTest.java

Fix problem with clearing collections for running tests
Added same credentials for login in tests
Instrumented

Fix problem with clearing collections for running tests

---

android-lib/src/main/java/com/kinvey/android/cache/QueryHelper.java
java-api-core/src/com/kinvey/java/query/MongoQueryFilter.java

The goal of the task is to remove operator replacement logic
Removed operator replacement logic
Instrumented

MLIBZ-2080 not() operator - should it transform Mongo operators or add $not Mongo operator

---

java-api-core/test/com/kinvey/java/query/QueryTest.java

Changes for testNot in java-api-core
Changes for testNot in java-api-core
Changes for testNot in java-api-core
Instrumented

Changes for testNot in java-api-core

---

android-lib/src/main/java/com/kinvey/android/store/UserStore.java

Deprecate social login methods
Social login methods deprecated in favor of using MIC
Instrumented

MLIBZ 2858 deprecate social login methods

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/AggregationTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/file/FileStoreTest.java
java-api-core/src/com/kinvey/java/cache/KinveyCachedClientCallback.java
java-api-core/src/com/kinvey/java/network/NetworkManager.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/BaseFileStore.java
java-api-core/src/com/kinvey/java/store/ReadPolicy.java
java-api-core/src/com/kinvey/java/store/StoreType.java
java-api-core/src/com/kinvey/java/store/requests/data/AggregationRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/ReadRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/AbstractReadCountRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/AbstractReadRequest.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadSingleRequest.java

Create AUTO DataStore type
Created AUTO DataStore type, and deprecated CACHE DataStore type
Instrumented

MLIBZ-2850 CreateAUTO data store type

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/push/PushTest.java
android-lib/src/main/java/com/kinvey/android/push/AbstractPush.java

Send extra info for push notifications using FCM
added new service parameter for AbstractPush.PushRegistration class
Instrumented

MLIBZ-2924 Send extra info for push notifications using FCM

---

android-lib/src/androidTest/java/com/kinvey/androidTest/model/EntitySet.java
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java

Implement AUTO data store tests
Added all possible blocks of tests from doc with test cases
Instrumented

MLIBZ-2896 Implement AUTO data store tests

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java
android-lib/src/main/java/com/kinvey/android/store/UserStore.java

Correctly handle missing or null refresh token
added checking for `refresh_token==null`
Instrumented

MLIBZ-2823 Correctly handle missing or null refresh token

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java

Implement tests for AUTO store type from `Create` block
Added tests for REMOVE and REMOVEBYID blocks
Instrumented

MLIBZ-2969 Implement tests for AUTO store type from `Create` block

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java

Investigate working of `AUTO` store type with `LOCAL_THEN_NETWORK` write policy
Added some tests for checking how `AUTO` store type works with `LOCAL_THEN_NETWORK` write policy
Instrumented

MLIBZ-2970 Add `write_policy` for `AUTO` store type

---

android-lib/src/main/java/com/kinvey/android/Client.java
java-api-core/src/com/kinvey/java/AbstractClient.java
java-api-core/src/com/kinvey/java/core/KinveyHeaders.java

Implement ability to set API version
Added new variable in `AbstractClient` for change API version from `kinvey.property`
Instrumented

MLIBZ-3028 Add ability to set API version

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java
java-api-core/src/com/kinvey/java/network/NetworkManager.java
java-api-core/src/com/kinvey/java/store/BaseDataStore.java
java-api-core/src/com/kinvey/java/store/requests/data/read/ReadCountRequest.java

Add new DataStore.count method with query object
Added new DataStore.count method with query object
Instrumented

MLIBZ - 2956 - Add new DataStore.count method with query object

---

android-lib/src/main/java/com/kinvey/android/store/DataStore.java
java-api-core/src/com/kinvey/java/dto/BatchList.java

Fixes in sdk api version settings logic.
Fix in switching sdk api version logic in `DataStore`  `save` request.  
Instrumented

Fixes in switching sdk api version logic.

---

java-api-core/src/com/kinvey/java/core/AbstractKinveyClientRequest.java
java-api-core/src/com/kinvey/java/core/KinveyClientRequestInitializer.java
java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java

Fix in token request format response.
Fix in token request format response.
Instrumented.

MLIBZ-3007, Implement multi-record insert, some fixes for token request

---

android-lib/build.gradle
android-lib/src/main/AndroidManifest.xml
android-lib/src/main/java/com/kinvey/android/UuidFactory.java
build.gradle

Enabled Android Lint checks in project.
Enabled Android Lint checks in project.
Instrumented.

MLIBZ-3091: Add Android Lint to project

---

android-lib/build.gradle
build.gradle
java-api-core/build.gradle

Added configuration for SDK distribution using `JitPack` repository.
Added configuration for SDK distribution using `JitPack` repository.
Instrumented.

MLIBZ-3097: SDK distribution

---

android-lib/build.gradle
android-lib/src/main/AndroidManifest.xml
android-lib/src/main/java/com/kinvey/android/AndroidJson.java
android-lib/src/main/java/com/kinvey/android/UuidFactory.java
android-lib/src/main/java/com/kinvey/android/async/AsyncBatchPushRequest.kt

Changes based on Lint report available at `android-lib/build/reports/lint-results.html`
- Dependencies upgrade
- Removing permission `android.permission.READ_PRIVILEGED_PHONE_STATE` since it's reserved for internal apps only (ProtectedPermission)
- Same tests

Lint fixes

---

android-lib/build.gradle
android-lib/src/main/java/com/kinvey/android/store/FileStore.kt

Minor improvement on FileStore
- `FileStore.kt`
- Same tests

Minor improvement on FileStore

---

.cirrus.yml
android-lib/build.gradle
android-lib/proguard-rules.pro
java-api-core/build.gradle

Changes to be able to run tests on Cirrus CI
- No code changes
- Same tests

MLIBZ-2832: Cirrus CI

---

LICENSE.txt

Check `LICENSE.txt` in the root project directory, if all licences are added to this file. 
Check `LICENSE.txt` in the root project directory, if all licences are added to this file. 
Instrumented.

MLIBZ-3093: Update license file

---

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/AsyncTaskTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/ClientBuilderTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/ClientTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/UserTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/cache/ClassHashTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/network/AsyncLinkedNetworkManagerTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultipleMultiInsertTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/PaginationTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreMockTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.kt

Increase code coverage

---

android-lib/build.gradle
android-lib/src/androidTest/java/com/kinvey/androidTest/TestRunner.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/BaseDataStoreMultiInsertTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultipleMultiInsertTest.kt
android-lib/src/main/java/com/kinvey/android/store/DataStore.kt
android-lib/src/main/java/com/kinvey/android/store/UserStore.kt
java-api-core/src/com/kinvey/java/model/KinveySaveBatchResponse.kt
java-api-core/src/com/kinvey/java/store/BaseDataStore.kt
java-api-core/src/com/kinvey/java/store/requests/data/save/CreateListBatchRequest.kt
java-api-core/test/com/kinvey/java/NetworkManagerTest.kt
java-api-core/test/com/kinvey/java/model/KinveySaveBatchResponseTest.kt
java-api-core/test/com/kinvey/java/store/request/save/SaveListBatchRequestTest.kt

Adding new create multiinsert method
Added create method only for kinvey api version 5
Instrumented

MLIBZ-3048 Multi record insert create

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.kt
java-api-core/src/com/kinvey/java/Constants.kt
java-api-core/src/com/kinvey/java/auth/KinveyAuthResponse.kt
java-api-core/src/com/kinvey/java/dto/BaseUser.kt

To get last login time need to call `getLastLoginTime()` from user object.
Added `getLastLoginTime()` to `BaseUser` class. This method returns a property `_kmd.llt` which hold information about the "Last login time" of the user. 
Instrumented

KDEV-688: Add last login time to kinvey meta data model

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTest.kt
java-api-core/src/com/kinvey/java/store/requests/data/save/CreateListBatchRequest.kt

The created items in the backend have some artificial ids, containing 'temp' and a guid.
Added removing ids from items for a create batch request and added saving returned items with new ids.
Instrumented

KDEV-782: Created items in the backend have some artificial ids, containing 'temp' and a guid

---

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultiInsertTest.kt
android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreSingleInsertTest.kt
java-api-core/src/com/kinvey/java/store/requests/data/save/CreateListBatchRequest.kt

We need to return a general error when trying to create items, which are with ids, which are already present in the local storage or there are some not unique ids in the passed array of items.
Added checking if items have uniq id, otherwise return `KinveyException` with `reason` field - `The array contains more than one entity with _id ${ids}`
Added checking if item with such id doesn't exist in local storage,  otherwise return  `KinveyException` with `reason` field - `An entity with _id ${ids} already exists`.
Also now in `KinveySaveBatchResponse` if a user tried to create 6 entities and had 5 errors and only 1 success item, he gets 5 errors and 1 entity in entities. Before the fix, the user could have 6 entities in success entities but 5 of them didn't have id or fields was empty or …

KDEV-897: Add validation for an existing item id when the data store type is not 'Network'
