java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java
Incorrect wording for extra user login (https://kinvey.atlassian.net/browse/MLIBZ-1823)
Update wrong text in the exception, since it goes through the UserStore now
Manual
=> fix: MLIBZ-1823 Incorrect wording for extra user login for Android

android-lib/src/main/java/com/kinvey/android/push/GCMPush.java, java-api-core/src/com/kinvey/java/core/KinveyClientRequestInitializer.java
Incorrect error text if trying to initialize GCM and user is not logged in or initialize KinveyClientRequest when app credentials are not required (https://kinvey.atlassian.net/browse/MLIBZ-1860)
Update text in error messages, since it goes through the UserStore now
Manual
=> refactor: MLIBZ-1860 Improving the error message strings

android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/store/UserStore.java, java-api-core/src/com/kinvey/java/dto/UserNameExists.java, java-api-core/src/com/kinvey/java/store/BaseUserStore.java, java-api-core/src/com/kinvey/java/store/requests/user/ForgotUsername.java, java-api-core/src/com/kinvey/java/store/requests/user/UserExists.java
Add 'requireAppCredentials' flag to 'user-forgot-username' and 'check-username-exists' requests. Improve tests accordingly.
(https://kinvey.atlassian.net/browse/MLIBZ-1883)
Added 'requireAppCredentials' to requests, added new DTO for 'check-username-exists' response.
JUnit
=> fix: MLIBZ-1883 Missed flag in 'user-forgot-username' and 'check-username-exists' requests

java-api-core/src/com/kinvey/java/store/BaseFileStore.java
When trying to upload a file with StoreType.CACHE and InputStream in parameters, getting an exception.
Save to cache before InputStream is closed.
JUnit
=> fix: MLIBZ-1888 Crash while uploading file with InputStream

java-api-core/src/com/kinvey/java/core/MediaHttpDownloader.java
File couldn't be downloaded if its size is zero. Got '416 Requested range not satisfiable' and the download was looping because of retrying to send new requests.
Check metadata size and don't add range header if it's empty.
JUnit
=> fix: MLIBZ-1893 File can't be downloaded if its size is zero

android-lib/javadoc/overview.html
An update relating to documentation. Fixes broken links in the Java Doc.
Updates dead links in android-lib/javadoc/overview.html.
Manual test of the links inside the HTML.
=> Replaced a few links leading to public_beta with up-to-date links.

java-api-core/src/com/kinvey/java/network/LinkedNetworkManager.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java, java-api-core/src/com/kinvey/java/query/AbstractQuery.java
Don't send empty query object
Remove sending empty query object
Instrumented
=> fix: MLIBZ-1945 Android SDK sends empty query object on get all

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/ClassHashTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/LongClassNameLongClassNameLongClassNameLongClassNameLongClassName.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person50.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person51.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person56.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java, android-lib/src/main/java/com/kinvey/android/cache/TableNameManager.java
Implemented possibility to use names longer than 56 symbols for realm tables.
Added support table for mapping class names which contains short class names (random 36 symbols in a string). Short class names are used for working with a realm. 
=> feat: MLIBZ-2093 Realm class name is too long error when using nested classes

android-lib/src/main/java/com/kinvey/android/Client.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
Added clearing cache tables (_acl and _kmd) before calling pull/sync
Added clearing cache tables (_acl and _kmd) before calling pull/sync
=> feat: MLIBZ-2140  Collection kmd grows exponentially every time a sync pull is called

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, java-api-core/src/com/kinvey/java/store/requests/data/PushRequest.java
Fixed BaseDataStore#pushblocking method
Collection name was saved not correctly. It was fixed.
Instrumented, manual.
=> fix: MLIBZ-2151 Android sdk 3.0.8 push() is throwing an exception

android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java, android-lib/src/main/java/com/kinvey/android/cache/TableNameManager.java
Add user data migration logic from 3.0.5 version
Added migration if user has old table name but doesn't have new table name (optimized name)
Checked manual in the test case:
User has 3.0.5 version. Also he has collection `Book` with some items and some items in `sync` collection in not pushed state. Class `Book` has inner class `Author`. User updated android kinvey library version to 3.0.9. After start application his inner tables was renamed to the new way. His data in `Book` and `sync` collection was saved and he can call `sync` to push his not synced items to the server. He shouldn't call `logout` to update table names.
=> feat: MLIBZ-2166 Upgrading from Android 3.0.5 to latest SDK crashes on data store methods

android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Exponential growth KDM every time a sync or pull is called was fixed
When autopagination was enabled, pull method has created new items in _kmd and _acl support tables even when items should be updated. It was fixed.
Manual
=> feat: MLIBZ-2140  kmd grows exponentially every time a sync or pull is called(autopagination)

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, java-api-core/src/com/kinvey/java/query/AbstractQuery.java
Customer is using an implicit AND of two equals fields, and is not getting the same result as before.
val query = kinveyClient.query()
query.equals("filedA", "A")
query.equals("filedB", "B")
val queryString = query.getQueryFilterJson(AndroidJsonFactory.getDefaultInstance())
Log.d("Kinvey", queryString)
Before:
{"filedA":"A","filedB":"B"}
After:
{"filedA":"A"}
Change when JSON object is closed, based on the number of filters that are set on the query.
Instrumented test.
=> MLIBZ-2227 Fix building of mongo query to support implicit and of two equals filters

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveySyncCallback.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java
Sync method throws an exception if Delta Cache is enabled
Changed response parser type to array
Instrumented test (check that sync method doesn't throw exception if Delta Cache is enabled), manual test
=> feat: MLIBZ-2241 Sync with delta set caching set to true fails with exception

android-lib/src/androidTest/java/com/kinvey/androidTest/store/FileStoreTest.java, android-lib/src/main/java/com/kinvey/android/store/FileStore.java, java-api-core/src/com/kinvey/java/LinkedResources/GetLinkedResourceClientRequest.java, java-api-core/src/com/kinvey/java/store/BaseFileStore.java
Fixed cached callback. User can get cached file path from FileMetaData object. 
Also a new method for downloading file was added. The new method has a OutputStream parameter for a cached file. 
Instrumented
=> feat: MLIBZ-2070 no file meta data returned from store type.cache and a request to the backend is always made

android-lib/src/androidTest/java/com/kinvey/androidTest/ClientBuilderTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/request/RequestTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, java-api-core/src/com/kinvey/java/AbstractClient.java, java-api-core/src/com/kinvey/java/core/AbstractKinveyClientRequest.java
`Client.setRequestTimeout` method didn't affect to request timeout. It was fixed.
Call `setRuestTimeout` was added  to `Client.Builder.build` method.
Default request timeout was updated from 20s to 60s.
Instrumented, manual.
=> feat: MLIBZ-2283 Fix setting request timeout

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
Not correct saving items to the cache if sync/pull methods are used with skip/limit parameters in a query. It happens because items are cleared not in correct order before sync/pull.
Added sort by `_kmd.ect` for getting items from the cache.
Instrumented
=> feat: MLIBZ-2134 Fix sync/pull with skip/limit in a query

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java
Add testing around sort order for removing pages from cache
Checked that SDK pulls the items in correct order from the server skip limit is used in pull/sync query.
Checked that SDK finds the items in the cache in the correct order if skip limit is used in find method.
Checked that SDK removes the correct items from cache in pull/sync process if skip limit is used in pull/sync query.
Instrumented
=> feat: MLIBZ-2298 Add testing around sort order for removing pages from cache

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
For correct work `skip` parameter a user have to add sorting to the query. 
If autopagination is enabled, sorting should work correct without any additinal action from the user side.
Added sorting for tests with items order checking. Also sorting was added in autopagination logic. 
In autopagination case SDK didn't lose user data without sorting, but had not correct items order as well.
Instrumented
=> feat: MLIBZ-2318 Add sorting for tests with items order checking

java-api-core/src/com/kinvey/java/core/AbstractKinveyReadRequest.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Updated `pullBlocking` signature
`cache.get(query)` is needed only in case if `DeltaSetCache` is enabled. This call was removed for the case `DeltaSetCache` is disabled. It affects the time for Pull request initializing.
Manual, Instrumented
=> feat: MLIBZ-2302 Investigate performance of realm cache inserts

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, java-api-core/src/com/kinvey/java/model/KinveyMetaData.java
User could not set null to the nested object and save it. SDK has ignored that nested object was changed to null.
SDK has ignored fields with null objects, this logic was updated. Currently If an object has a field with a null object it will be saved to the realm object in the field with a null value.
Instrumented
=> feat: MLIBZ-2339 Add support for null nested objects

java-api-core/src/com/kinvey/java/core/AbstractKinveyClientRequest.java, java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java, java-api-core/src/com/kinvey/java/store/requests/user/LogoutSoftRequest.java
After an auth token expires and the refresh token flow starts, the attempt to retrieve a new refresh token would exception out. This is due to a hard logout of the active user.
Change logout in refresh token retry to be soft, and re-initialize the request to ensure latest auth token is used.
Manual testing to initiate refresh token flow.
=> MLIBZ-2269 

android-lib/src/androidTest/java/com/kinvey/androidTest/model/PersonLongListName.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/PersonOver63CharsInFieldName.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
If ArrayList<String> field with the long name (more than 7 chars) is used in a data model class, SDK had the exception like "Class name is too long".
SDK creates the additional table with the short name for keeping Lists. Before this logic worked only for embedded objects.
Instrumented
=> feat: MLIBZ-2328 Add support for long names in fields with List type

android-lib/src/androidTest/java/com/kinvey/androidTest/LiveServiceTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/request/RequestTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java, java-api-core/src/com/kinvey/java/Constants.java, java-api-core/src/com/kinvey/java/model/KinveyMetaData.java, java-api-core/src/com/kinvey/java/store/requests/user/LogoutRequest.java
Currently, metadata such as `_kmd` and `_acl` are being added to objects that are embedded in an entity. This needs to be removed to match the behavior of the other SDKs.
`_kmd` and `_acl` fields were removed from objects that are embedded in an entity.
If an entity has `_kmd` and `_acl` fields in embedded objects they will be ignored and won't be sent to the server in the next push and won't be saved from the server in the pull.
=> feat: MLIBZ-2392 Remove metadata storage on embedded objects

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheManagerTest.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java, java-api-core/src/com/kinvey/java/cache/ICacheManager.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
`DataStore#clear` does not clear metadata for data synced in previous SDK versions.
Added new method `clearCollection` to CacheManager. The method deletes the collection and creates its new version. Current method `clear` just deletes realm file, this logic was saved. Logic for `DataStore.clear` was updated from `CacheManager#clear` to `CacheManager#clearCollection`.
Instrumented, Manual. Manual testing is necessary in this case because we have to update library version from 3.0.5 to latest version, it's impossible to check in the tests. Anyway, the small test for checking was added, the test checks that `CacheManager#clearCollection` doesn't crash.
=> feat: MLIBZ-2185 Clear does not clear metadata for data synced in previous sdk versions

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveRequest.java
Improved SaveListRequest performance for StoreType.CACHE
Implemented bulk saving pushed items to the cache
Instrumented
=> feat: MLIBZ-2103 Improve SaveListRequest for StoreType.CACHE

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/async/AsyncPushRequest.java, android-lib/src/main/java/com/kinvey/android/async/CallableAsyncPushRequestHelper.java, java-api-core/src/com/kinvey/java/Constants.java, java-api-core/src/com/kinvey/java/store/requests/data/PushRequest.java, java-api-core/src/com/kinvey/java/sync/SyncManager.java
Item isn't deleted from the backend after update delete operations with store type.sync.
Precondition: 
Create dataStore with StoreType.SYNC
Steps:
1. Create item (state1) and push it to the server 
2. Update item (state2)
3. Delete item
4. Sync with the server
Actual Result:
In the store we have the item (state1).
Expected result:
Item should be removed (from both the cache and the backend).
`DELETE` sync request will be added to a stack of sync requests even if `SAVE` request already exists in the stack.
Instrumented
=> feat: MLIBZ-2430 Item isn't deleted from the backend after update delete operations with store type.sync

android-lib/src/androidTest/java/com/kinvey/androidTest/ClientBuilderTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, java-api-core/src/com/kinvey/java/AbstractClient.java
Enable instance.id in properties file
Added instance.id  as a possible parameter to the properties file.
If `setBaseUrl` and `setInstanceId` are used in the `Client.Builder`, the order of these methods call is important, last option will be used. For examle `(Client.Builder(mContext).setBaseUrl("BaseUrl").setInstanceID("TestInstanceId").build())`, in this case `instanceID` will be used, if `setBaseUrl` will be after `setInstanceID` then `baseUrl` parameter will be used.
For properties file, the options order doesn't matter, in all cases, `instanceID` will be used if it exists.
=> feat: MLIBZ-2433 Enable instance.id in properties file

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/AsyncPullRequest.java, android-lib/src/main/java/com/kinvey/android/store/DataStore.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Change how auto-pagination is enabled: from `dataStore.setAutoPagination(true);` to `pull(query, pageSize, callback);`.
Removed the isAutoPaginationEnabled boolen field from BaseDataStore.
Added new methods: `pullBlocking(Query query, int pageSize)` to the BaseDataStore and 
`pull(int pageSize, KinveyPullCallback<T> callback)`,  `pull(Query query, int pageSize, KinveyPullCallback<T> callback)`  to the DataStore classes.
Updated tests.
Instrumented.
=> feat: MLIBZ-2414 Change how auto-pagination is enabled

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveyPullCallback.java, android-lib/src/androidTest/java/com/kinvey/androidTest/callback/CustomKinveySyncCallback.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java, android-lib/src/main/java/com/kinvey/android/AsyncPagedPullRequest.java, android-lib/src/main/java/com/kinvey/android/AsyncPullRequest.java, android-lib/src/main/java/com/kinvey/android/async/AsyncPushRequest.java, android-lib/src/main/java/com/kinvey/android/store/DataStore.java, android-lib/src/main/java/com/kinvey/android/sync/KinveyPullCallback.java, android-lib/src/main/java/com/kinvey/android/sync/KinveyPullResponse.java, android-lib/src/main/java/com/kinvey/android/sync/KinveySyncCallback.java, java-api-core/src/com/kinvey/java/model/KinveyPullResponse.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
`KinveyPullResponse` has to return count of pulled items instead of list of items. 
The PR has breaking changes:
Users have to: 
1. Remove old import for `KinveyPullResponse`
`import com.kinvey.android.sync.KinveyPullResponse;`
and add a new one `import com.kinvey.java.model.KinveyPullResponse;`.
2. Remove GenericType from `KinveyPullResponse<Book> `, `KinveySyncCallback<Book>`, `KinveyPullCallback<Book>`, it should look like `KinveyPullResponse`, `KinveySyncCallback`, `KinveyPullCallback`.
The method  `public List<T> getResult()` was changed to `public int getCount()` in the `KinveyPullResponse` class.
Instrumented
=> feat: MLIBZ-2387 Update auto pagination to meet design spec

android-lib/src/androidTest/java/com/kinvey/androidTest/model/InternalUserEntity.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/TestUser.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, android-lib/src/main/java/com/kinvey/android/store/UserStore.java, java-api-core/src/com/kinvey/java/AbstractClient.java, java-api-core/src/com/kinvey/java/auth/Credential.java, java-api-core/src/com/kinvey/java/auth/CredentialManager.java, java-api-core/src/com/kinvey/java/auth/KinveyAuthRequest.java, java-api-core/src/com/kinvey/java/store/BaseUserStore.java, java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java, java-api-core/src/com/kinvey/java/store/requests/user/Update.java, java-api-core/test/com/kinvey/java/BaseUserTest.java, java-api-core/test/com/kinvey/java/core/KinveyMockUnitTest.java
Extending user class with properties of different class cause an exception
Updated auth response parsing. Now the SDK gets user class as a model for response parsing. Previously the model for response parsing had only `id` and `_kmd` fields, other primitive fields were got as fields from GenericJson and it didn't work for GenericJson fields in the user model class.
Instrumented
=> feat: MLIBZ-2447 Extending user class with properties of different class cause an exception

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Implement server side delta set tests
Added server side delta set tests
Added fixes: 
1. `pull` returns count of changed items for delta set instead of count of all items from the cache.
2. `find(query)` with delta set returns a correct value, before the `find` returned all items (query was absent)
3. fixed NPE in the list of exceptions in ReadResponse.
Instrumented
=> feat: MLIBZ-2470 Test server side delta set use cases

android-lib/src/androidTest/java/com/kinvey/androidTest/TestManager.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaCacheTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java, java-api-core/src/com/kinvey/java/core/KinveyJsonResponseException.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Steps to reproduce:
1. Pull with enabled deltaset - this would create an entry in the _QueryCache table
2. Create more than 10000 items in the server
3. Pull - this pull should use deltaset
Expected result: The second pull starts with a _deltaset request, which returns an error becaus of too many changed items. Next the pull should send a regular GET requst, if auto-pagination is turned on, it should use it, otherwise it should not.
Actual result: the second pull uses _deltaset, but after the error is returned it does not try to make a regular GET
Check Exceptions after unsuccessful Delta Set request. 
Instrumented tests
=> feat: MLIBZ-2542 When the changed items are more than 10000 with deltaset, the pull does not try a regular get request after

android-lib/src/androidTest/java/com/kinvey/androidTest/MICLoginTest.java, java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java, java-api-core/src/com/kinvey/java/store/requests/user/GetMICTempURL.java
MIC fixes for `scope=openid` and `clientID`
Added `?scope=openid` in the end of url in GetMICTempURL request.
Updated clientID position for LoginToTempURL creation in the MICLoginToTempURL method.
Unit tests
=> feat: MLIBZ-2576 MIC fixes for `scope=openid` and `clientID`

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/Person.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
Using 'int' primitive type in class model and store SYNC and CACHE throws an exception
Added сonverting long to int type when the SDK gets an object from the realm file
Instrumented
=> feat: MLIBZ-2472 Using 'int' primitive type in class model and store SYNC and CACHE throws an exception

android-lib/src/androidTest/java/com/kinvey/androidTest/store/DeltaSetNewTest.java, java-api-core/src/com/kinvey/java/Constants.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
When a deltaset specific error occurs, deltaset request is not retried on next attempts to pull/sync
Steps to reproduce:
1. Disable deltaset at the backend
2. Pull
3. Pull
4. Pull
Expected result: The first pull makes a regular GET and enter a value in the _QueryCache table, the next one attempts _deltaset request, but it fails for an error, so a regular GET is again made and its value overrides the lastRequestAt value in the _QueryCache table. The third request does exactly the same as the second one
Actual result: The first pull does what is expected, the second uses deltaset and then regular GET, but records a new entry for the query in _QueryCache table, so now it has 2 entries. The third pull directly makes a regular GET instead of first using deltaset. These also make their own …
=> feat: MLIBZ-2563 Add updating query cache item if it exists instead of creating new

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/TempIdTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java
Currently, we are allowing Realm to create a GUID for the ID of a locally-created entity. It would be better to have more control of that format, such as prepending the ID with "temp_" or something like this, so that we can more definitively tell when we have created an object locally that has to get a permanent ID from the backend.
Change temporary ID format for locally created entities.
Instrumented
=> feat: MLIBZ-2559 Change how we format temporary IDs for locally-created entities

android-lib/src/androidTest/java/com/kinvey/androidTest/store/PaginationTest.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java
Steps to reproduce:
1. Create 5 items with some property value - e.g. name = name1
2. Create 3000 items with another value - e.g. name = name2
3. Pull() or Sync() with AP = 1000
4. Check the db - all 3005 items should be there
5. Delete all items with name=name2 from the backend
6. Pull() or Sync() with AP=1000
Expected result: All 3000 items with name=name2 are deleted from the cache
Actual result: The AP pull gets only the 5 items with name = name1, which were not deleted from the backend. Not all items with name =name2, however, are deleted from cache. The number of actually deleted items from the cache = the AP size(1000) - the result of the _count request from the AP pull() - in our case 5. So from all 3005 items, after the pull from step 6, there are 2005 items in the cache, the …
=> feat: MLIBZ-2577 Using Auto-pagination does not delete all items in the cache

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/TempIdTest.java, android-lib/src/main/java/com/kinvey/android/async/AsyncPushRequest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java, java-api-core/src/com/kinvey/java/store/requests/data/PushRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteIdsRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteQueryRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/delete/DeleteSingleRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveRequest.java, java-api-core/src/com/kinvey/java/sync/SyncManager.java, java-api-core/src/com/kinvey/java/sync/dto/SyncItem.java, java-api-core/src/com/kinvey/java/sync/dto/SyncRequest.java
Right now, requests for the sync queue are only being saved as a SAVE or DELETE. It would be better to expose out what type of request we are pursuing (POST/PUT/DELETE) in the queue itself, in order to be able to replace temporary IDs with permanent IDs easier.
Changed sync items types from `SAVE or DELETE` to `POST/PUT/DELETE`. `SAVE` type was saved for backward compatibility with previous implementation.
Instrumented
=> feat: MLIBZ-2558 Change how sync queue stores request information

android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheAggregationTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheRealDataTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/cache/CacheTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/cache/QueryTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/EntityForInQueryTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/LongPrimitiveListInPerson.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/ModelWithDifferentTypeFields.java, android-lib/src/androidTest/java/com/kinvey/androidTest/model/PersonArray.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
Increase code coverage of /cache source files
Added tests for  RealmCache class, some bugs were filed for this class: `MLIBZ-2644`, `MLIBZ-2647`. 
ClassHash contains untested only migration methods and one unused untested method.
QueryHelper's methods have tests except for tests for exceptions which can be thrown from reflection call, we can't add tests for them.
RealmCacheManager contains untested only migration methods.
TableNameManager doesn't have untested methods.
Instrumented
=> feat: MLIBZ-2609 Increase code coverage of cache source files

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/store/UserStore.java
The goal of the task is to process error message from redirect_uri
In UserStore#onOAuthCallbackReceived fixed logic of redirect_uri processing
Instrumented
=> feat: MLIBZ-2530 Handle OAuth errors in redirect uri responses after MIC login flow

android-lib/src/androidTest/java/com/kinvey/androidTest/model/Location.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/network/QueryNetworkTest.java
The goal of the task is to add tests for Query class methods which aren't supported by the cache but have to work with StoreType.NETWORK
Added test class QueryNetworkTest.java and model class Location.java
Instrumented
=> MLIBZ-2601 Give feedback  Add tests for Query class methods which aren't supported by the cache but have to work with StoreType.NETWORK

android-lib/src/androidTest/java/com/kinvey/androidTest/model/DateExample.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.java
The goal of the task is to find why time from Date object in milliseconds before saving to the DataStore isn't equaled time after getting the entity from the DataStore
Add test for entity with date and fix RealmCache
Instrumented
=> MLIBZ-2643 Time from Date object in milliseconds before saving to the DataStore isn't equaled time after getting the entity from the DataStore

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/cache/ClassHash.java
The goal of the task is to find why the SDK throws the exception after getting saved entity, which has an array with self-reference type in entity data model.
Fix the condition in ClassHash.createSchemeFromClass
Instrumented
=> MLIBZ-2647 Self-reference data model with an array

android-lib/src/main/java/com/kinvey/android/store/UserStore.java
The goal of the task is deprecate loginWithAuthorizationCodeAPI() method for automated authorization grant flow
Deprecated loginWithAuthorizationCodeAPI()  in favor of a `loginWithMIC()` method 
Instrumented
=> MLIBZ-2762 Deprecate `loginWithAuthorizationCodeAPI()` method for automated authorization grant flow

java-api-core/src/com/kinvey/java/store/requests/user/GetMICAccessToken.java, java-api-core/test/com/kinvey/java/BaseUserTest.java
Currently the path for retrieving the access token is hardcoded and changes to the MIC API version do not get applied. This fix makes sure that the MIC API version that's set from the code is being applied.
`mKinveyClient.setMICApiVersion("3");`  this call now makes sure that the token request goes to the correct path.
The test reflecting this from `BaseUserTest.java` file has been fixed and adjusted.
=> Access Token path might be affected by the MIC API version.

android-lib/src/main/java/com/kinvey/android/AsyncClientRequest.java, android-lib/src/main/java/com/kinvey/android/store/DataStore.java, java-api-core/src/com/kinvey/java/AbstractClient.java, java-api-core/src/com/kinvey/java/annotations/ReferenceHelper.java, java-api-core/src/com/kinvey/java/core/AbstractKinveyClientRequest.java, java-api-core/src/com/kinvey/java/network/NetworkManager.java, java-api-core/src/com/kinvey/java/store/BaseDataStore.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListRequest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveRequest.java
Make network requests async
Changed requests for async
Instrumented
=> MLIBZ - 2882 Make network requests async

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, android-lib/src/main/java/com/kinvey/android/KinveyHandlerThread.java, java-api-core/src/com/kinvey/java/AbstractClient.java
Use multi-threading model to handle network requests
Added logic with pool of threads for requests
Instrumented
=> MLIBZ-2891 Use multi-threading model to handle network requests

android-lib/src/main/java/com/kinvey/android/store/UserStore.java
Create overload of `loginWithMIC` without `temporaryURI` parameter
Added an overload that removes this parameter, and deprecated a version of `loginWithMIC` that takes a `temporaryURI` 
Instrumented
=> MLIBZ-2933 Create overload of `loginWithMIC` without `temporaryURI` parameter

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, android-lib/src/main/java/com/kinvey/android/cache/RealmCacheManager.java, java-api-core/src/com/kinvey/java/AbstractClient.java, java-api-core/src/com/kinvey/java/Constants.java, java-api-core/src/com/kinvey/java/auth/Credential.java, java-api-core/src/com/kinvey/java/auth/KinveyAuthResponse.java, java-api-core/src/com/kinvey/java/dto/BaseUser.java, java-api-core/src/com/kinvey/java/store/UserStoreRequestManager.java, java-api-core/test/com/kinvey/java/core/KinveyMockUnitTest.java, java-api-core/test/com/kinvey/java/testing/MockKinveyJsonClient.java
If login to an app, then to close the app and open it again `client.getActiveUser()` returns only user id, even if user contained some additional filled fields (userName etc). 
Added saving user info to realm table, except auth_token. 
Instrumented
=> MLIBZ-2859: Client.getActiveUser() returns only userId

android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/DefaultKinveyClientCallback.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/DefaultKinveyVoidCallback.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/MockClient.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/MockHttpErrorTransport.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/MockHttpTransport.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/MockedClient.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreMockTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.java, android-lib/src/main/java/com/kinvey/android/Client.java, android-lib/src/main/java/com/kinvey/android/store/UserStore.java
Create mock responses to simulate user and login server errors (5xx).
Added `MockClient` for mocking server responses for `UserStoreMockTest`. 
Checked that user logs out when the client object is initialising if the SDK gets HttpResponseException.
Checked that user gets in callback status code and error messages. 
Instrumented
=> MLIBZ-2843: Create mock responses to simulate user and login server errors (5xx)

.travis.yml, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/BaseDataStoreTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertItemsOrderTestKotlin.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTest.java, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTestKotlin.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTestOrderKotlin.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultipleMultiInsertTestKotlin.kt, android-lib/src/main/java/com/kinvey/android/store/DataStore.kt, java-api-core/src/com/kinvey/java/AbstractClient.kt, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListBatchRequest.kt
Fix for issue if in a batch of multi-insert requests, if a whole batch fails, the response to the whole operation is an error.
Made fixes to solve issue if in a batch of multi-insert requests, if a whole batch fails, the response to the whole operation is an error.
Instrumented.
=> MLIBZ-3137: In a batch of multi-insert requests, if a whole batch fails, the response to the whole operation is an error

.cirrus.yml, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertOfflinePushTestKotlin.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreTest.java, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveListBatchRequest.kt, java-api-core/src/com/kinvey/java/store/requests/data/save/SaveRequest.kt
Fix for `DataStore.save` failing for network error invokes the `onFailure` handler.
* Fix for `DataStore.save` failing for network error invokes the `onFailure` handler, now it returns onSuccess if item was saved in cache if was no connection, for `AUTO` or `SYNC` store types.
* Made some correction in tests: `DataStoreTest#testSaveConnectErrorAuto`, `DataStoreTest#testSaveNoAccess` that checking old `DataStore.save` behavior, that was changed.
* Added new tests to check new `DataStore.save` logic behaviour.
Instrumented.
=> MLIBZ-3140: datastore.save failing for network error invokes the onFailure handler - Android

android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTest.kt, android-lib/src/main/java/com/kinvey/android/store/DataStore.kt
The `create` function will not work for future API versions bigger than 5.
Update checking API version.
Instrumented.
=> KDEV-783: Batch create function will not work for API versions bigger than 5

android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/BaseDataStoreMultiInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreMultiInsertTest.kt, java-api-core/src/com/kinvey/java/model/KinveyBatchInsertError.kt, java-api-core/test/com/kinvey/java/model/KinveySaveBatchResponseTest.kt, java-api-core/test/com/kinvey/java/model/KinveySyncSaveBatchResponseTest.kt
The error message from the server is not returned, when some of the items fail.
Updated `KinveyBatchInsertError` class: removed `code` and `errorMessage` fields, now it extends `KinveyErrorResponse`, it adds `error`, `description`, `debug` fields. 
Instrumented.
=> KDEV-779: The error message from the server is not returned, when some of the items fail

android-lib/build.gradle, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/DataStoreCountHeaderTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/BaseDataStoreTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/datastore/DataStoreTest.kt, android-lib/src/main/java/com/kinvey/android/cache/RealmCache.kt, android-lib/src/main/java/com/kinvey/android/store/DataStore.kt, java-api-core/src/com/kinvey/java/Constants.kt, java-api-core/src/com/kinvey/java/cache/ICache.kt, java-api-core/src/com/kinvey/java/core/AbstractKinveyReadRequest.kt, java-api-core/src/com/kinvey/java/model/KinveyReadResponse.kt, java-api-core/src/com/kinvey/java/network/NetworkManager.kt, java-api-core/src/com/kinvey/java/store/BaseDataStore.kt, java-api-core/src/com/kinvey/java/store/requests/data/ReadRequest.kt, java-api-core/src/com/kinvey/java/store/requests/data/read/ReadAllRequest.kt, java-api-core/src/com/kinvey/java/store/requests/data/read/ReadIdsRequest.kt, java-api-core/src/com/kinvey/java/store/requests/data/read/ReadQueryRequest.kt, java-api-core/test/com/kinvey/java/store/request/read/ReadQueryRequestTest.kt
Add an option to send 'X-Kinvey-Include-Items-Count' header and get the returned items in 'X-Kinvey-Items-Count' returned header.
- Added `isAddCountHeader` parameter to `DataStore`. `isAddCountHeader` is false by default. If `isAddCountHeader` is true, all callbacks `KinveyReadCallback` have not null `count` field with count of all items by a query. `limit` and `skip` query parameters are ignored.
- Added `findWithCount(query: Query, callback: KinveyReadCallback<T>)` method to `DataStore`. The method returns count of all items by the query in  `count` field in `KinveyReadCallback`. This method ignores `isAddCountHeader` parameter from `DataStore`.
- Added `count` field to `KinveyReadCallback` which shows count of all items in collection for a query.  If `isAddCountHeader` is false or …
=> KDEV 547: Return items count with GET requests

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/BaseDataStoreMultiInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultiInsertItemsOrderTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultiInsertOfflinePushTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultiInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultipleMultiInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreSingleInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/user/UserStoreTest.kt, android-lib/src/main/java/com/kinvey/android/async/AsyncCreateRequest.kt, android-lib/src/main/java/com/kinvey/android/store/DataStore.kt, java-api-core/src/com/kinvey/java/network/NetworkManager.kt, java-api-core/src/com/kinvey/java/store/BaseDataStore.kt, java-api-core/src/com/kinvey/java/store/requests/data/save/CreateRequest.kt
The `create` function should support also a single item.
Added `create(entity: T, callback: KinveyClientCallback<T>)` function to `DataStore` class.
Instrumented.
=> KDEV-784: Create function should support also a single item

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/request/HeaderTest.kt, android-lib/src/main/java/com/kinvey/android/store/DataStore.kt, build.gradle
The default KCS api version should be `5`
Updated the default KCS api version to `5`
Instrumented.
=> KDEV-843: Update the default KCS api version to 5

android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/BaseDataStoreMultiInsertTest.kt, android-lib/src/androidTest/java/com/kinvey/androidTest/store/data/multiinsert/DataStoreMultiInsertTest.kt, java-api-core/src/com/kinvey/java/store/requests/data/save/CreateListBatchRequest.kt
Pull operation fails with `InvalidOperation. You must push all pending sync items before new data is pulled. Call push() on the data store instance to push pending items, or purge() to remove them.` after using the new `create` function and an `Auto` store type.
Removed adding operation to sync manager for store type `Auto` if no errors with network requests.
Instrumented.
=> fix: KDEV-950: Not able to pull after batch create
